# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Math Utility Repo applying CI # Đặt tên cho tất cả các lệnh ở dưới
                                    # Tên của danh sách các công việc cần làm khi ai đó 
                                    # Push code, sửa code của kho 
on:
  push:                             # Khi ai đó sửa code
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:                               # Thì làm những việc dưới đây
  build:                            # Build cái app 

    runs-on: ubuntu-latest          # 1. Mượn cái server bên Mỹ, cài OS Ubuntu
    steps:
    - uses: actions/checkout@v3     # 2. Download code về cái server của bạn
    - name: Set up JDK 20           # 3. Cài JDK trên server vừa 
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven (tạo .jar .war)    # 4. Mượn maven và chạy lệnh huyền thoại mvn package
      run: mvn -B package --file pom.xml
    - name: Build project with Maven
      run: mvn -B package --file pom.xml # Quá trình build sẽ cần đến file cấu hình pom.xml
      
    - name: Distribute jar-war file # Gửi file .jar .war đi đâu, CD nhảy vào ...
      run: mkdir staging && cp target/*.jar staging # tạo thư mục staging chứa file .jar .war sau khi build      
     
    - name: Make hyperlink to jar-war file # Tạo hyperlink để download build 
      uses: actions/upload-artifact@v1
      with:
          name: Hay-Downlod-Jar-O-Day # Đây là đường link trỏ tới file .jar .war
          path: staging               # nếu được build thành công 
